name: t20-tue-simpeg

channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - numpy
  - scipy
  - matplotlib
  - jupyter
  - ipywidgets>=0.6.0
  - mkl
  - pip
  - pip:
    - git+https://github.com/simpeg/simpeg.git@transform-dc-updates
